%fname='../train/MOT17-02-FRCNN/img1/000275.jpg'
%draw_bb(fname,457,458,30,104);

% layer = lstmLayer('InputSize', 2, 'OutputSize', 8, 'OutputMode', 'last');
% 
% options = trainingOptions('sgdm', 'ExucutionEnvironment', 'gpu',...
%     'InitialLearnRate', 0.002, 'LearnRateSchedule', 'piecewise',...
%     'LearnRateDropFactor', 0.1, 'LearnRatePeriod', 10,...
%     'MaxEpochs', 50, 'MiniBatchSize', '64', 'Momentum', 0.9,...
%     'Shuffle', 'every-epoch', 'Verbose', 1, 'VerboseFrequency', 1,...
%     'Plots', 'training-progress0');

